/* 
 * WebAPI - Area Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: management
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ACUtils.AXRepository.ArxivarNextManagement.Client.SwaggerDateConverter;

namespace ACUtils.AXRepository.ArxivarNextManagement.Model
{
    /// <summary>
    /// Class of credentials for IX Services request
    /// </summary>
    [DataContract]
    public partial class IxCredentialsForRequestDTO :  IEquatable<IxCredentialsForRequestDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IxCredentialsForRequestDTO" /> class.
        /// </summary>
        /// <param name="credentialsId">Saved credentials id.</param>
        /// <param name="endpoint">Endpoint.</param>
        /// <param name="username">Username.</param>
        /// <param name="password">Password.</param>
        public IxCredentialsForRequestDTO(int? credentialsId = default(int?), string endpoint = default(string), string username = default(string), string password = default(string))
        {
            this.CredentialsId = credentialsId;
            this.Endpoint = endpoint;
            this.Username = username;
            this.Password = password;
        }
        
        /// <summary>
        /// Saved credentials id
        /// </summary>
        /// <value>Saved credentials id</value>
        [DataMember(Name="credentialsId", EmitDefaultValue=false)]
        public int? CredentialsId { get; set; }

        /// <summary>
        /// Endpoint
        /// </summary>
        /// <value>Endpoint</value>
        [DataMember(Name="endpoint", EmitDefaultValue=false)]
        public string Endpoint { get; set; }

        /// <summary>
        /// Username
        /// </summary>
        /// <value>Username</value>
        [DataMember(Name="username", EmitDefaultValue=false)]
        public string Username { get; set; }

        /// <summary>
        /// Password
        /// </summary>
        /// <value>Password</value>
        [DataMember(Name="password", EmitDefaultValue=false)]
        public string Password { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IxCredentialsForRequestDTO {\n");
            sb.Append("  CredentialsId: ").Append(CredentialsId).Append("\n");
            sb.Append("  Endpoint: ").Append(Endpoint).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IxCredentialsForRequestDTO);
        }

        /// <summary>
        /// Returns true if IxCredentialsForRequestDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of IxCredentialsForRequestDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IxCredentialsForRequestDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CredentialsId == input.CredentialsId ||
                    (this.CredentialsId != null &&
                    this.CredentialsId.Equals(input.CredentialsId))
                ) && 
                (
                    this.Endpoint == input.Endpoint ||
                    (this.Endpoint != null &&
                    this.Endpoint.Equals(input.Endpoint))
                ) && 
                (
                    this.Username == input.Username ||
                    (this.Username != null &&
                    this.Username.Equals(input.Username))
                ) && 
                (
                    this.Password == input.Password ||
                    (this.Password != null &&
                    this.Password.Equals(input.Password))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CredentialsId != null)
                    hashCode = hashCode * 59 + this.CredentialsId.GetHashCode();
                if (this.Endpoint != null)
                    hashCode = hashCode * 59 + this.Endpoint.GetHashCode();
                if (this.Username != null)
                    hashCode = hashCode * 59 + this.Username.GetHashCode();
                if (this.Password != null)
                    hashCode = hashCode * 59 + this.Password.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
