/* 
 * WebAPI - Area Management
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: management
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ACUtils.AXRepository.ArxivarNextManagement.Client.SwaggerDateConverter;

namespace ACUtils.AXRepository.ArxivarNextManagement.Model
{
    /// <summary>
    /// Class of IX credentials with parents
    /// </summary>
    [DataContract]
    public partial class IxCredentialsTreeDTO :  IEquatable<IxCredentialsTreeDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IxCredentialsTreeDTO" /> class.
        /// </summary>
        /// <param name="credentials">Credentials.</param>
        /// <param name="parentCredentials">Parent credentials.</param>
        public IxCredentialsTreeDTO(IxCredentialsDTO credentials = default(IxCredentialsDTO), IxCredentialsTreeDTO parentCredentials = default(IxCredentialsTreeDTO))
        {
            this.Credentials = credentials;
            this.ParentCredentials = parentCredentials;
        }
        
        /// <summary>
        /// Credentials
        /// </summary>
        /// <value>Credentials</value>
        [DataMember(Name="credentials", EmitDefaultValue=false)]
        public IxCredentialsDTO Credentials { get; set; }

        /// <summary>
        /// Parent credentials
        /// </summary>
        /// <value>Parent credentials</value>
        [DataMember(Name="parentCredentials", EmitDefaultValue=false)]
        public IxCredentialsTreeDTO ParentCredentials { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IxCredentialsTreeDTO {\n");
            sb.Append("  Credentials: ").Append(Credentials).Append("\n");
            sb.Append("  ParentCredentials: ").Append(ParentCredentials).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IxCredentialsTreeDTO);
        }

        /// <summary>
        /// Returns true if IxCredentialsTreeDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of IxCredentialsTreeDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IxCredentialsTreeDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Credentials == input.Credentials ||
                    (this.Credentials != null &&
                    this.Credentials.Equals(input.Credentials))
                ) && 
                (
                    this.ParentCredentials == input.ParentCredentials ||
                    (this.ParentCredentials != null &&
                    this.ParentCredentials.Equals(input.ParentCredentials))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Credentials != null)
                    hashCode = hashCode * 59 + this.Credentials.GetHashCode();
                if (this.ParentCredentials != null)
                    hashCode = hashCode * 59 + this.ParentCredentials.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
