/* 
 * WebAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: data
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ACUtils.AXRepository.ArxivarNext.Client;
using ACUtils.AXRepository.ArxivarNext.Model;

namespace ACUtils.AXRepository.ArxivarNext.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IAddressBookNoteApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// This call deletes an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookNoteId"></param>
        /// <returns></returns>
        void AddressBookNoteDeleteAddressBookNote (int? addressBookNoteId);

        /// <summary>
        /// This call deletes an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookNoteId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddressBookNoteDeleteAddressBookNoteWithHttpInfo (int? addressBookNoteId);
        /// <summary>
        /// This call returns all the notes created in an addressbook item
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookId">System Id of the addressbook</param>
        /// <returns>List&lt;AddressBookNoteDTO&gt;</returns>
        List<AddressBookNoteDTO> AddressBookNoteGetByAddressBookId (int? addressBookId);

        /// <summary>
        /// This call returns all the notes created in an addressbook item
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookId">System Id of the addressbook</param>
        /// <returns>ApiResponse of List&lt;AddressBookNoteDTO&gt;</returns>
        ApiResponse<List<AddressBookNoteDTO>> AddressBookNoteGetByAddressBookIdWithHttpInfo (int? addressBookId);
        /// <summary>
        /// This call creates a note for an addressBook
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns></returns>
        void AddressBookNoteInsertAddressBookNote (AddressBookNoteDTO body);

        /// <summary>
        /// This call creates a note for an addressBook
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddressBookNoteInsertAddressBookNoteWithHttpInfo (AddressBookNoteDTO body);
        /// <summary>
        /// This call creates a note for an addressBook
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns></returns>
        void AddressBookNoteInsertAddressBookNote (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note);

        /// <summary>
        /// This call creates a note for an addressBook
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddressBookNoteInsertAddressBookNoteWithHttpInfo (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note);
        /// <summary>
        /// This call updates an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns></returns>
        void AddressBookNoteUpdateAddressBookNote (AddressBookNoteDTO body);

        /// <summary>
        /// This call updates an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddressBookNoteUpdateAddressBookNoteWithHttpInfo (AddressBookNoteDTO body);
        /// <summary>
        /// This call updates an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns></returns>
        void AddressBookNoteUpdateAddressBookNote (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note);

        /// <summary>
        /// This call updates an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddressBookNoteUpdateAddressBookNoteWithHttpInfo (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// This call deletes an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookNoteId"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddressBookNoteDeleteAddressBookNoteAsync (int? addressBookNoteId);

        /// <summary>
        /// This call deletes an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookNoteId"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddressBookNoteDeleteAddressBookNoteAsyncWithHttpInfo (int? addressBookNoteId);
        /// <summary>
        /// This call returns all the notes created in an addressbook item
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookId">System Id of the addressbook</param>
        /// <returns>Task of List&lt;AddressBookNoteDTO&gt;</returns>
        System.Threading.Tasks.Task<List<AddressBookNoteDTO>> AddressBookNoteGetByAddressBookIdAsync (int? addressBookId);

        /// <summary>
        /// This call returns all the notes created in an addressbook item
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookId">System Id of the addressbook</param>
        /// <returns>Task of ApiResponse (List&lt;AddressBookNoteDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<AddressBookNoteDTO>>> AddressBookNoteGetByAddressBookIdAsyncWithHttpInfo (int? addressBookId);
        /// <summary>
        /// This call creates a note for an addressBook
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddressBookNoteInsertAddressBookNoteAsync (AddressBookNoteDTO body);

        /// <summary>
        /// This call creates a note for an addressBook
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddressBookNoteInsertAddressBookNoteAsyncWithHttpInfo (AddressBookNoteDTO body);
        /// <summary>
        /// This call creates a note for an addressBook
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddressBookNoteInsertAddressBookNoteAsync (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note);

        /// <summary>
        /// This call creates a note for an addressBook
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddressBookNoteInsertAddressBookNoteAsyncWithHttpInfo (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note);
        /// <summary>
        /// This call updates an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddressBookNoteUpdateAddressBookNoteAsync (AddressBookNoteDTO body);

        /// <summary>
        /// This call updates an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddressBookNoteUpdateAddressBookNoteAsyncWithHttpInfo (AddressBookNoteDTO body);
        /// <summary>
        /// This call updates an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddressBookNoteUpdateAddressBookNoteAsync (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note);

        /// <summary>
        /// This call updates an addressbook note
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddressBookNoteUpdateAddressBookNoteAsyncWithHttpInfo (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class AddressBookNoteApi : IAddressBookNoteApi
    {
        private ACUtils.AXRepository.ArxivarNext.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AddressBookNoteApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AddressBookNoteApi(String basePath)
        {
            this.Configuration = new ACUtils.AXRepository.ArxivarNext.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ACUtils.AXRepository.ArxivarNext.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AddressBookNoteApi"/> class
        /// </summary>
        /// <returns></returns>
        public AddressBookNoteApi()
        {
            this.Configuration = ACUtils.AXRepository.ArxivarNext.Client.Configuration.Default;

            ExceptionFactory = ACUtils.AXRepository.ArxivarNext.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AddressBookNoteApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AddressBookNoteApi(ACUtils.AXRepository.ArxivarNext.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ACUtils.AXRepository.ArxivarNext.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ACUtils.AXRepository.ArxivarNext.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ACUtils.AXRepository.ArxivarNext.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ACUtils.AXRepository.ArxivarNext.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// This call deletes an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookNoteId"></param>
        /// <returns></returns>
        public void AddressBookNoteDeleteAddressBookNote (int? addressBookNoteId)
        {
             AddressBookNoteDeleteAddressBookNoteWithHttpInfo(addressBookNoteId);
        }

        /// <summary>
        /// This call deletes an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookNoteId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> AddressBookNoteDeleteAddressBookNoteWithHttpInfo (int? addressBookNoteId)
        {
            // verify the required parameter 'addressBookNoteId' is set
            if (addressBookNoteId == null)
                throw new ApiException(400, "Missing required parameter 'addressBookNoteId' when calling AddressBookNoteApi->AddressBookNoteDeleteAddressBookNote");

            var localVarPath = "/api/AddressBookNote/{addressBookNoteId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (addressBookNoteId != null) localVarPathParams.Add("addressBookNoteId", this.Configuration.ApiClient.ParameterToString(addressBookNoteId)); // path parameter
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteDeleteAddressBookNote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// This call deletes an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookNoteId"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddressBookNoteDeleteAddressBookNoteAsync (int? addressBookNoteId)
        {
             await AddressBookNoteDeleteAddressBookNoteAsyncWithHttpInfo(addressBookNoteId);

        }

        /// <summary>
        /// This call deletes an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookNoteId"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> AddressBookNoteDeleteAddressBookNoteAsyncWithHttpInfo (int? addressBookNoteId)
        {
            // verify the required parameter 'addressBookNoteId' is set
            if (addressBookNoteId == null)
                throw new ApiException(400, "Missing required parameter 'addressBookNoteId' when calling AddressBookNoteApi->AddressBookNoteDeleteAddressBookNote");

            var localVarPath = "/api/AddressBookNote/{addressBookNoteId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (addressBookNoteId != null) localVarPathParams.Add("addressBookNoteId", this.Configuration.ApiClient.ParameterToString(addressBookNoteId)); // path parameter
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteDeleteAddressBookNote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// This call returns all the notes created in an addressbook item 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookId">System Id of the addressbook</param>
        /// <returns>List&lt;AddressBookNoteDTO&gt;</returns>
        public List<AddressBookNoteDTO> AddressBookNoteGetByAddressBookId (int? addressBookId)
        {
             ApiResponse<List<AddressBookNoteDTO>> localVarResponse = AddressBookNoteGetByAddressBookIdWithHttpInfo(addressBookId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// This call returns all the notes created in an addressbook item 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookId">System Id of the addressbook</param>
        /// <returns>ApiResponse of List&lt;AddressBookNoteDTO&gt;</returns>
        public ApiResponse< List<AddressBookNoteDTO> > AddressBookNoteGetByAddressBookIdWithHttpInfo (int? addressBookId)
        {
            // verify the required parameter 'addressBookId' is set
            if (addressBookId == null)
                throw new ApiException(400, "Missing required parameter 'addressBookId' when calling AddressBookNoteApi->AddressBookNoteGetByAddressBookId");

            var localVarPath = "/api/AddressBookNote/ByAddressBookId/{addressBookId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (addressBookId != null) localVarPathParams.Add("addressBookId", this.Configuration.ApiClient.ParameterToString(addressBookId)); // path parameter
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteGetByAddressBookId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<AddressBookNoteDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<AddressBookNoteDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<AddressBookNoteDTO>)));
        }

        /// <summary>
        /// This call returns all the notes created in an addressbook item 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookId">System Id of the addressbook</param>
        /// <returns>Task of List&lt;AddressBookNoteDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<AddressBookNoteDTO>> AddressBookNoteGetByAddressBookIdAsync (int? addressBookId)
        {
             ApiResponse<List<AddressBookNoteDTO>> localVarResponse = await AddressBookNoteGetByAddressBookIdAsyncWithHttpInfo(addressBookId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// This call returns all the notes created in an addressbook item 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="addressBookId">System Id of the addressbook</param>
        /// <returns>Task of ApiResponse (List&lt;AddressBookNoteDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<AddressBookNoteDTO>>> AddressBookNoteGetByAddressBookIdAsyncWithHttpInfo (int? addressBookId)
        {
            // verify the required parameter 'addressBookId' is set
            if (addressBookId == null)
                throw new ApiException(400, "Missing required parameter 'addressBookId' when calling AddressBookNoteApi->AddressBookNoteGetByAddressBookId");

            var localVarPath = "/api/AddressBookNote/ByAddressBookId/{addressBookId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (addressBookId != null) localVarPathParams.Add("addressBookId", this.Configuration.ApiClient.ParameterToString(addressBookId)); // path parameter
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteGetByAddressBookId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<AddressBookNoteDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<AddressBookNoteDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<AddressBookNoteDTO>)));
        }

        /// <summary>
        /// This call creates a note for an addressBook 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns></returns>
        public void AddressBookNoteInsertAddressBookNote (AddressBookNoteDTO body)
        {
             AddressBookNoteInsertAddressBookNoteWithHttpInfo(body);
        }

        /// <summary>
        /// This call creates a note for an addressBook 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> AddressBookNoteInsertAddressBookNoteWithHttpInfo (AddressBookNoteDTO body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");

            var localVarPath = "/api/AddressBookNote";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteInsertAddressBookNote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// This call creates a note for an addressBook 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddressBookNoteInsertAddressBookNoteAsync (AddressBookNoteDTO body)
        {
             await AddressBookNoteInsertAddressBookNoteAsyncWithHttpInfo(body);

        }

        /// <summary>
        /// This call creates a note for an addressBook 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> AddressBookNoteInsertAddressBookNoteAsyncWithHttpInfo (AddressBookNoteDTO body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");

            var localVarPath = "/api/AddressBookNote";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteInsertAddressBookNote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// This call creates a note for an addressBook 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns></returns>
        public void AddressBookNoteInsertAddressBookNote (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note)
        {
             AddressBookNoteInsertAddressBookNoteWithHttpInfo(id, addressBookId, date, authorCompleteName, author, note);
        }

        /// <summary>
        /// This call creates a note for an addressBook 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> AddressBookNoteInsertAddressBookNoteWithHttpInfo (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");
            // verify the required parameter 'addressBookId' is set
            if (addressBookId == null)
                throw new ApiException(400, "Missing required parameter 'addressBookId' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");
            // verify the required parameter 'date' is set
            if (date == null)
                throw new ApiException(400, "Missing required parameter 'date' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");
            // verify the required parameter 'authorCompleteName' is set
            if (authorCompleteName == null)
                throw new ApiException(400, "Missing required parameter 'authorCompleteName' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");
            // verify the required parameter 'author' is set
            if (author == null)
                throw new ApiException(400, "Missing required parameter 'author' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");
            // verify the required parameter 'note' is set
            if (note == null)
                throw new ApiException(400, "Missing required parameter 'note' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");

            var localVarPath = "/api/AddressBookNote";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarFormParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // form parameter
            if (addressBookId != null) localVarFormParams.Add("addressBookId", this.Configuration.ApiClient.ParameterToString(addressBookId)); // form parameter
            if (date != null) localVarFormParams.Add("date", this.Configuration.ApiClient.ParameterToString(date)); // form parameter
            if (authorCompleteName != null) localVarFormParams.Add("authorCompleteName", this.Configuration.ApiClient.ParameterToString(authorCompleteName)); // form parameter
            if (author != null) localVarFormParams.Add("author", this.Configuration.ApiClient.ParameterToString(author)); // form parameter
            if (note != null) localVarFormParams.Add("note", this.Configuration.ApiClient.ParameterToString(note)); // form parameter
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteInsertAddressBookNote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// This call creates a note for an addressBook 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddressBookNoteInsertAddressBookNoteAsync (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note)
        {
             await AddressBookNoteInsertAddressBookNoteAsyncWithHttpInfo(id, addressBookId, date, authorCompleteName, author, note);

        }

        /// <summary>
        /// This call creates a note for an addressBook 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> AddressBookNoteInsertAddressBookNoteAsyncWithHttpInfo (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");
            // verify the required parameter 'addressBookId' is set
            if (addressBookId == null)
                throw new ApiException(400, "Missing required parameter 'addressBookId' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");
            // verify the required parameter 'date' is set
            if (date == null)
                throw new ApiException(400, "Missing required parameter 'date' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");
            // verify the required parameter 'authorCompleteName' is set
            if (authorCompleteName == null)
                throw new ApiException(400, "Missing required parameter 'authorCompleteName' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");
            // verify the required parameter 'author' is set
            if (author == null)
                throw new ApiException(400, "Missing required parameter 'author' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");
            // verify the required parameter 'note' is set
            if (note == null)
                throw new ApiException(400, "Missing required parameter 'note' when calling AddressBookNoteApi->AddressBookNoteInsertAddressBookNote");

            var localVarPath = "/api/AddressBookNote";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarFormParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // form parameter
            if (addressBookId != null) localVarFormParams.Add("addressBookId", this.Configuration.ApiClient.ParameterToString(addressBookId)); // form parameter
            if (date != null) localVarFormParams.Add("date", this.Configuration.ApiClient.ParameterToString(date)); // form parameter
            if (authorCompleteName != null) localVarFormParams.Add("authorCompleteName", this.Configuration.ApiClient.ParameterToString(authorCompleteName)); // form parameter
            if (author != null) localVarFormParams.Add("author", this.Configuration.ApiClient.ParameterToString(author)); // form parameter
            if (note != null) localVarFormParams.Add("note", this.Configuration.ApiClient.ParameterToString(note)); // form parameter
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteInsertAddressBookNote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// This call updates an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns></returns>
        public void AddressBookNoteUpdateAddressBookNote (AddressBookNoteDTO body)
        {
             AddressBookNoteUpdateAddressBookNoteWithHttpInfo(body);
        }

        /// <summary>
        /// This call updates an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> AddressBookNoteUpdateAddressBookNoteWithHttpInfo (AddressBookNoteDTO body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");

            var localVarPath = "/api/AddressBookNote";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteUpdateAddressBookNote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// This call updates an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddressBookNoteUpdateAddressBookNoteAsync (AddressBookNoteDTO body)
        {
             await AddressBookNoteUpdateAddressBookNoteAsyncWithHttpInfo(body);

        }

        /// <summary>
        /// This call updates an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> AddressBookNoteUpdateAddressBookNoteAsyncWithHttpInfo (AddressBookNoteDTO body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");

            var localVarPath = "/api/AddressBookNote";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteUpdateAddressBookNote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// This call updates an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns></returns>
        public void AddressBookNoteUpdateAddressBookNote (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note)
        {
             AddressBookNoteUpdateAddressBookNoteWithHttpInfo(id, addressBookId, date, authorCompleteName, author, note);
        }

        /// <summary>
        /// This call updates an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> AddressBookNoteUpdateAddressBookNoteWithHttpInfo (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");
            // verify the required parameter 'addressBookId' is set
            if (addressBookId == null)
                throw new ApiException(400, "Missing required parameter 'addressBookId' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");
            // verify the required parameter 'date' is set
            if (date == null)
                throw new ApiException(400, "Missing required parameter 'date' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");
            // verify the required parameter 'authorCompleteName' is set
            if (authorCompleteName == null)
                throw new ApiException(400, "Missing required parameter 'authorCompleteName' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");
            // verify the required parameter 'author' is set
            if (author == null)
                throw new ApiException(400, "Missing required parameter 'author' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");
            // verify the required parameter 'note' is set
            if (note == null)
                throw new ApiException(400, "Missing required parameter 'note' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");

            var localVarPath = "/api/AddressBookNote";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarFormParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // form parameter
            if (addressBookId != null) localVarFormParams.Add("addressBookId", this.Configuration.ApiClient.ParameterToString(addressBookId)); // form parameter
            if (date != null) localVarFormParams.Add("date", this.Configuration.ApiClient.ParameterToString(date)); // form parameter
            if (authorCompleteName != null) localVarFormParams.Add("authorCompleteName", this.Configuration.ApiClient.ParameterToString(authorCompleteName)); // form parameter
            if (author != null) localVarFormParams.Add("author", this.Configuration.ApiClient.ParameterToString(author)); // form parameter
            if (note != null) localVarFormParams.Add("note", this.Configuration.ApiClient.ParameterToString(note)); // form parameter
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteUpdateAddressBookNote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// This call updates an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddressBookNoteUpdateAddressBookNoteAsync (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note)
        {
             await AddressBookNoteUpdateAddressBookNoteAsyncWithHttpInfo(id, addressBookId, date, authorCompleteName, author, note);

        }

        /// <summary>
        /// This call updates an addressbook note 
        /// </summary>
        /// <exception cref="ACUtils.AXRepository.ArxivarNext.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="addressBookId"></param>
        /// <param name="date"></param>
        /// <param name="authorCompleteName"></param>
        /// <param name="author"></param>
        /// <param name="note"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> AddressBookNoteUpdateAddressBookNoteAsyncWithHttpInfo (int? id, int? addressBookId, DateTime? date, string authorCompleteName, int? author, string note)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");
            // verify the required parameter 'addressBookId' is set
            if (addressBookId == null)
                throw new ApiException(400, "Missing required parameter 'addressBookId' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");
            // verify the required parameter 'date' is set
            if (date == null)
                throw new ApiException(400, "Missing required parameter 'date' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");
            // verify the required parameter 'authorCompleteName' is set
            if (authorCompleteName == null)
                throw new ApiException(400, "Missing required parameter 'authorCompleteName' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");
            // verify the required parameter 'author' is set
            if (author == null)
                throw new ApiException(400, "Missing required parameter 'author' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");
            // verify the required parameter 'note' is set
            if (note == null)
                throw new ApiException(400, "Missing required parameter 'note' when calling AddressBookNoteApi->AddressBookNoteUpdateAddressBookNote");

            var localVarPath = "/api/AddressBookNote";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarFormParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // form parameter
            if (addressBookId != null) localVarFormParams.Add("addressBookId", this.Configuration.ApiClient.ParameterToString(addressBookId)); // form parameter
            if (date != null) localVarFormParams.Add("date", this.Configuration.ApiClient.ParameterToString(date)); // form parameter
            if (authorCompleteName != null) localVarFormParams.Add("authorCompleteName", this.Configuration.ApiClient.ParameterToString(authorCompleteName)); // form parameter
            if (author != null) localVarFormParams.Add("author", this.Configuration.ApiClient.ParameterToString(author)); // form parameter
            if (note != null) localVarFormParams.Add("note", this.Configuration.ApiClient.ParameterToString(note)); // form parameter
            // authentication (Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddressBookNoteUpdateAddressBookNote", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

    }
}
